### ISSUE TITLE
No audio on pi 3

### ISSUE THREAD

**Issue by leshow** [5schatten/LibreELEC-RR#6]
I installed this on the rpi3 and no audio was coming out in the kodi interface or in any of the emulation frontends. I switched the add-on settings for RRConfig to pulse and I'm able to get menu noises, but no game audio of any kind. I'm a little at a loss for what's happening here. I've checked the audio is unmuted

**Comment by 5schatten** [comment]
If your RPi has no sound output in Kodi you probably have selected a completely wrong audio device or output. Nevertheless without log files it's basically impossible to solve your problem. Have you read the FAQ and followed these steps? https://forum.libreelec.tv/thread/12662-libreelec-9-x-rr-emulationstation-retroarch-pegasus-dolphinqt-moonlight-chrome-s/?postID=94134#post94134

**Comment by leshow** [comment]
Yes, I have read this and selected PulseAudio, then rebooted. What logs would you like?

edit: it appears the audio is not working just in emulationstation/retroarch

**Comment by 5schatten** [comment]
Did you also select a proper audio device first in the config tool? Upload a logfile zip once you tried to run ES & RA and got no sound. Anyway the best way to "debug" this is to create an account in the LE forum and discuss it there.

**Comment by 5schatten** [comment]
I guess this can be closed then.
