### ISSUE TITLE
ZFS support

### ISSUE THREAD

**Issue by digitalsanity** [5schatten/LibreELEC-RR#8]
Could we get zfs added to the module list? :)

**Comment by 5schatten** [comment]
What exactly do you mean by module list? This one? https://zfsonlinux.org/ Btw. looks like it's atm not compatible to linux 5.2.y anyway https://github.com/zfsonlinux/zfs/releases/tag/zfs-0.8.1

**Comment by digitalsanity** [comment]
1. Include spl and zfs in buildroot, can probably pull directly from this
project:
- https://github.com/mistifyio/mistify-os/tree/master/package/mistify/spl
- https://github.com/mistifyio/mistify-os/tree/master/package/mistify/zfs

2. Build kernel with CONFIG_SPL and CONFIG_ZFS

Gentoo has some static-install steps that may help with debugging--
https://wiki.gentoo.org/wiki/ZFS

# Thoughts-

Currently working on an alternate route -- running LibreELEC-RR within a
privileged docker container.  I have standard LibreELEC working this way
successfully using Ubuntu desktop as the 'host' on a RockPro64.  Basically,
you get ZFS/desktop/browser/docker on the host level.  LibreELEC runs as a
systemd service that is started by a desktop icon -- on RockPro64 this
shuts down X and starts kodi-gbm.  If you enable the service, it boots
directly into LibreELEC but still has the Ubuntu kernel/packages/etc on the
host.  Power off from LibreELEC brings you back to the X desktop.

Front-end + back-end with 8x drives on ZFS in a briefcase with all of the
other popular HTPC docker containers in one go with e.g.:
http://github.com/digitalsanity/htpc/

Regards,
Jason

**Comment by TheChuckster** [comment]
I might be able to take a look at this later. I don't like running LibreELEC-RR inside a docker container, since I am about to use Docker containers to run Steam inside LibreELEC-RR (which is 64-bit and Steam only supports 32-bit).

**Comment by 5schatten** [comment]
PR welcome :+1:
